navbar 비율 조정 및 Sign In 없어지는 이슈 수정, 전체적인 비율 수정
undefined-for-now/undefined pull request #29
Opened 2023-07-30 01:51 UTC by poohtime1

요청하신 이슈 수정 및 브라우저 사이즈를 줄였을때 생기는 비율 버그를 수정하였습니다.

2023-07-30 04:32 UTC, avelynhc commented on frontend/src/App.js
Is there any reason why we do not use a CSS file for style? If not, can we make it consistent and extract every style-related code to a CSS file?"

2023-07-30 04:33 UTC, avelynhc commented on frontend/src/components/GamesCards.jsx
Is there any reason why we do not use a CSS file for styles? If not, can we make it consistent and extract every style-related code to a CSS file?"

2023-07-30 04:34 UTC, avelynhc commented on frontend/src/components/Navbar.jsx
Please remove space on line 18.

2023-07-30 04:35 UTC, avelynhc commented on frontend/src/components/Navbar2.jsx
Is there any reason why we do not use a CSS file for styles? If not, can we make it consistent and extract every style-related code to a CSS file?"

2023-07-30 04:49 UTC, avelynhc commented on frontend/src/components/RecentlyCards.jsx
> +                  <button style={{"width": "135px"}} className='border-white bg-amber-400 text-white mx-2 absolute bottom-4'>GAME START</button>
Is there any reason why we do not use a CSS file for styles? If not, can we make it consistent and extract every style-related code to a CSS file?

2023-07-30 04:51 UTC, avelynhc requested changes
Could you please add @HyoanMoon for frontend code review going forward? Thanks!

2023-08-01 00:06 UTC, HyoanMoon reviewed
Can you resolve conflict?

2023-08-01 00:25 UTC, avelynhc commented
@poohtime1  @HyoanMoon 
These are a few things to consider if you do NOT want to use a CSS file:
- In-line styles are a bit faster but performance difference is very low.
- How are you going to implement reusable style code? A bit redundant.
- We already have the Index.css file, so the CSS file needs to be downloaded anyway.
- The browser will cache the CSS file for the first time, so it won't affect performance later."

2023-08-07 23:55 UTC, merged